name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer==1.5.0

      - name: Force stable python-for-android version
        run: |
          pip install python-for-android==2023.9.16

      - name: Clean old builds
        run: |
          rm -rf .buildozer
          rm -rf ~/.buildozer

      - name: Build APK
        run: |
          export P4A_NDK_VERSION=25b
          export P4A_BUILD_DIR=$HOME/.local/share/python-for-android
          buildozer -v android debug
