name: Build Path APK

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-22.04


    steps:


    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17


    - name: Verify Java
      run: |
        java -version
        echo $JAVA_HOME


    - name: Setup Android SDK
      uses: android-actions/setup-android@v3


    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses || true


    - name: Install Android packages
      run: |

        sdkmanager \
        "platform-tools" \
        "platforms;android-33" \
        "build-tools;33.0.2" \
        "cmdline-tools;latest"


    - name: Install Buildozer
      run: |

        python3 -m pip install --upgrade pip

        pip3 install buildozer

        pip3 install cython==0.29.36


    - name: Build APK
      run: |

        buildozer android release


    - name: Upload APK
      uses: actions/upload-artifact@v4

      with:

        name: Path-update-APK

        path: bin/*.apk
